### ISSUE TITLE
Allow re-tallying

### ISSUE THREAD

**Issue by orestisfl** [kth-tcs/trustfull-demonstrator#12]
Split from #9:

```
Exception in thread "main" com.verificatum.protocol.ProtocolError: Attempting to shuffle in a used session!
```

**Comment by monperrus** [comment]
Important. Are you working on it?

**Comment by orestisfl** [comment]
@monperrus Yes!

Just to add more context: it's possible to start a new election but after having the `ciphertexts` it's not possible to re-tally them through the script.
