### ISSUE TITLE
add verification of identities in the demo workflow

### ISSUE THREAD

**Issue by monperrus** [kth-tcs/trustfull-demonstrator#19]
currently in the demo, anybody can vote

**Comment by algomaster99** [comment]
@palmskog and Arve (I cannot find his GitHub handle) put this forth in the meeting. They suggested that we could either have our own authentication system or use OAuth servers of KTH, Google, GitHub, or any other service.

I had a question about the implementation though. We basically need two things from the authentication.
1. Only verified voters vote.
2. There is exactly one vote per verified user.

How do we keep a check for the latter? One way to do so is to map the identity of the voter to the vote which defeats the purpose of the e-voting system. Any ideas for this?

**Comment by palmskog** [comment]
@algomaster99 @arolle we are at this point mostly interested in implementation of the "only verified voters vote" part, using something customizable like OAuth. There could be a simple database or flat file that defines what credentials are verified, e.g., username/password-hash pairs.

In our planned formal model, we will add tracking of cryptographic identities of voters into a vote collection server, but for the current demonstrator we are mostly interested in seeing the exchange of messages between voters / web server / authentication server.

**Comment by algomaster99** [comment]
> seeing the exchange of messages between voters / web server / authentication server.

Sounds like a plan. I can start to work on it.

**Comment by algomaster99** [comment]
Fixed by #29
